const ERROR_WRONG_DATA_STATUS_CODE = 400;
const ERROR_NOT_FOUND_STATUS_CODE = 404;
const ERROR_INTERNAL_STATUS_CODE = 500;

module.exports = {
  ERROR_WRONG_DATA_STATUS_CODE,
  ERROR_NOT_FOUND_STATUS_CODE,
  ERROR_INTERNAL_STATUS_CODE,
};
